name: build docs

on:
  push:
    tags:
      - "v*.*.*"

  pull_request:
    branches: [main, master]

  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install hatch
        run: pip install -U hatch hatchling

      - name: build docs
        run: hatch run docs:build

      - name: deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.event_name != 'pull_request'
        with:
          branch: gh-pages
          folder: docs/_build/html
          token: ${{ secrets.GITHUB_TOKEN }}
