name: check code

on:
  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: install hatch
        run: pip install -U hatch

      - name: test codestyle
        run: hatch run lint:style

      - name: test typing
        run: hatch run lint:typing

  scan-code:
    runs-on: ubuntu-latest
    needs: [check-code]
    if: github.event_name != 'pull_request'
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: run sonar-scanner
        uses: sonarsource/sonarqube-scan-action@v6
        env:
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
